version: "3"

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: psyoblade/data-engineer-mysql:1.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d
  notebook:
    container_name: notebook
    hostname: notebook
    image: psyoblade/data-engineer-notebook:1.7.5
    depends_on:
      - mysql
    user: root
    privileged: true
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
    ports:
      - "4040-4049:4040-4049"
      - "8080:8080"
      - "8888:8888"

networks:
  default:
    name: ssm_seoul_spark_network
