version: "3"

services:
  ubuntu:
    container_name: ubuntu
    image: psyoblade/data-engineer-ubuntu:20.04
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./ubuntu/example:/example
  mysql:
    container_name: mysql
    image: psyoblade/data-engineer-mysql:1.3
    depends_on:
      - notebook
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d

networks:
  default:
    name: ssm_seoul_docker_network

